# Generated by Django 4.1 on 2022-08-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('emp_status', models.CharField(choices=[('Regular', 'Regular'), ('Contractor', 'Contractor')], max_length=255)),
                ('country', models.CharField(choices=[('Denmark', 'Denmark'), ('Malaysia', 'Malaysia'), ('Taiwan', 'Taiwan')], max_length=255)),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
